spring:  
  application:
    name: discovery-service

server:  
  port: ${PORT:8761}
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 30000
    responseCacheUpdateIntervalMs: 3000

security:
 basic:
   enabled: true
 user:
   name: admin
   password: admin123